sudo: required
dist: trusty

os:
 - linux
matrix:
 exclude:
# Only do coverity or coverage build on Linux when the compiler is gcc
  - os: linux
    compiler: clang
    env: COVERITY=1
    env: COVERAGE=1
# Don't build with clang on Linux
  - os: linux
    compiler: clang
compiler: 
- gcc

before_script: 
- if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y; fi
- if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get update; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" && "$CXX" == "g++" ]]; then sudo apt-get -y install qt5-default qttools5-dev-tools libssl-dev; fi
- $CXX --version


script: 
- mkdir build_blackchocobo
- cd build_blackchocobo
- qmake ../Black_Chocobo.pro
- make -j2

language: cpp

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "B4xjY+hcZOob6hGLx8b5Ykxk+8sN9M+XwfnuhRReR1YRFvXZdcUUiL/VusDM0iapUGhkuvbO0AQEeLPaC69uBNdxQsBJFGFMzrHZGEtuBFl44SJB+lZGRTVemj3AZ4f5aQvTkKFbt7M+/sjkWa6ZP6EHdrAN2XCp4emrwKBApO4="

addons:
  coverity_scan:
    project:
      name: "sithlord48/blackchocobo"
      description: "Final Fantasy VII Save Editor"
    notification_email: sithlord48@gmail.com
    build_command_prepend: "qmake Black_Chocobo.pro"
    build_command:   "make -j 4"
    branch_pattern: coverity_scan
